# Generated by Django 4.0.3 on 2022-03-23 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_burger_id_alter_salad_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDish',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salads', models.ManyToManyField(to='dishes.salad')),
            ],
        ),
    ]
