# Generated by Django 4.0.3 on 2022-03-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_alter_maindish_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
