# Generated by Django 4.0.3 on 2022-03-23 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDishTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maindish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dishes.maindish')),
                ('tags', models.ManyToManyField(to='dishes.tag')),
            ],
        ),
    ]
